{% set version = "1.7.5" %}

package:
  name: nanoget
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nanoget/nanoget-{{ version }}.tar.gz
  sha256: 1560008f4aef16bd9e0a355d7f96f12e30a9b34e2c27d564716005751ad6f9da

build:
  number: 0
  skip: True  # [py27]

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - pandas >=0.22.0
    - numpy
    - biopython
    - pysam >0.10.0.0
    - nanomath

test:
  imports:
    - nanoget

about:
  home: https://github.com/wdecoster/nanoget
  license: MIT License
  summary: 'Functions to extract information from Oxford Nanopore sequencing data and alignments.'
  license_family: MIT
